version: "3.3"
services:
  db:
    restart: always
    image: postgres
    hostname: digitalbeing_db
    environment:
      POSTGRES_DB: digitalbeing
      POSTGRES_USER: digitalbeing
      POSTGRES_PASSWORD: digitalbeing_default_pw
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql