version: "3.9"
services:
  bot:
    build: .
    volumes:
      - "./:/DigitalBeing"
    depends_on:
      - "db"
    ports:
      - "65535:65535"
      - "65532:65532"

  db:
    restart: always
    image: postgres
    hostname: digitalbeing_db
    environment:
      POSTGRES_DB: digitalbeing
      POSTGRES_USER: digitalbeing
      POSTGRES_PASSWORD: digitalbeing_default_pw
    ports:
      - "5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql